services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: family7
      POSTGRES_PASSWORD: family7
      POSTGRES_DB: family7
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
