packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@expo/schema-utils@57.0.2'
  - expo-build-properties@57.0.5
  - expo-updates@57.0.7
